### ISSUE TITLE
Signal Bot not online, won't join room

### ISSUE THREAD

**Issue by Just-Insane** [mautrix/signal#120]
I'm having an issue getting the signal bot to join. I'm not seeing any obvious errors, in fact, my issue seems very similar to #116.

I have tried with both encryption enabled and disabled.

I also have basically the same setup with the Instagram bot (docker, localhost), and it is working perfectly.

**Comment by Hu0Q** [comment]
Hey, I suppose you ve followed the docker installation guide of the mautrix signal repo. I had the same problem after I had installed it as described in the instructions. After the installation I invited the bot and he didn't join. I couldn't see anything in the logs except a network error (trying to connect to appservice) in the matrix synapse logs. If this is also your problem then you should be able to solve it with the following solution. To solve the problem I changed the docker-compose.yml file that the mautrix-signal container exposes the port 29328 to the host like following (only add the both lines  *ports: -29328:29328*): 
```
version: "3.7"

services:
  mautrix-signal:
    container_name: mautrix-signal
    image: dock.mau.dev/mautrix/signal
    restart: unless-stopped
    volumes:
    - ./bridge:/data
    - ./signald:/signald
    ports:
    - 29328:29328
    depends_on:
    - signald
  signald:
    container_name: signald
    image: docker.io/finn/signald
    restart: unless-stopped
    volumes:
    - ./signald:/signald
  db:
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: <username>
      POSTGRES_DATABASE: <databasename>
      POSTGRES_PASSWORD: <password>
    volumes:
    - ./db:/var/lib/postgresql/data
```
After starting the containers with this config, the port 29328 had been exposed to the host and the matrix synapse service can reach it. 

If you run your matrix synapse instance also as a docker container you have to change something in the registration.yaml because the mautrix conatiner exposes its port to the host. However from the perspective of the matrix synapse container the url: http://localhost:29328 is the wrong one cause localhost doesn't address the host. That's why I had to change the line in the registration.yaml:      url: http://localhost:29328  into the following: url: http://<ip_of_gateway>:29328. The <ip_of_gateway> is the ip address of the host from the docker container perspective. To get this ip you have to inspect one container and look for its gateway ip. The matrix synapse container has to get access to the registration.yaml why I copied the registration.yaml file in the mounted data directory of the matrix container and put the path /data/registration.yaml in the homeserver.yaml file under the section app_services_config_files. 

Making this changes the signal bot joined the chat after an invitation. Don't forget some restarts after config changes :). Hope that helps.
