### ISSUE TITLE
Groups do not support encryption

### ISSUE THREAD

**Issue by verymilan** [mautrix/signal#224]
Hi there, I was trying to figure out of i have misconfigured something, but sadly there was no reply in the Matrix room. 
I have the following config right now:

```
    encryption:
        allow: true
        default: true
        key_sharing:
            allow: true
            require_cross_signing: false
            require_verification: true
```

This works for regular 1:1 chatrooms, but for groups, Element still displays a warning about Encryption not being supported and the setting is grayed out.
