### ISSUE TITLE
Configuration error error="appservice.database not configured"

### ISSUE THREAD

**Issue by Redskyer** [mautrix/signal#395]
Hi,

I'm using this configuration for over an year now, but for about 2 weeks, I get the following error and the container stops:
Configuration error error="appservice.database not configured"

Does anyone have an idea what's wrong or what I can do, to solve the problem?

This is the part of the config.yaml file. I've changed nothing:
```
.
.
.

# Application service host/registration related details.
# Changing these values requires regeneration of the registration.
appservice:
    # The address that the homeserver can use to connect to this appservice.
    address: http://192.168.112.11:29328
    
    # The hostname and port where this appservice should listen.
    hostname: 192.168.112.11
    port: 29328
    
    # Database config.
    database:
        # The database type. "sqlite3-fk-wal" and "postgres" are supported.
        type: postgres
        # The database URI.
        #   SQLite: A raw file path is supported, but `file:<path>?_txlock=immediate` is recommended.
        #           https://github.com/mattn/go-sqlite3#connection-string
        #   Postgres: Connection string. For example, postgres://user:password@host/database?sslmode=disable
        #             To connect via Unix socket, use something like postgres:///dbname?host=/var/run/postgresql
        uri: postgres://user:password@host/database?sslmode=disable
        # Maximum number of connections. Mostly relevant for Postgres.
        max_open_conns: 20
        max_idle_conns: 2
        # Maximum connection idle time and lifetime before they're closed. Disabled if null.
        # Parsed with https://pkg.go.dev/time#ParseDuration
        max_conn_idle_time: null
        max_conn_lifetime: null
    
    # The unique ID of this appservice.
    id: signal

.
.
.
```
