### ISSUE TITLE
Prometheus metrics not being updated?

### ISSUE THREAD

**Issue by Ma27** [mautrix/signal#453]
The metrics `bridge_connected` & `bridge_logged_in` are always `0` for Signal whereas they're - as expected `1` for the Whatsapp bridge.

Other metrics appear to work fine, e.g. `bridge_count_collection` & `bridge_messages_total` appear to be updated properly. I may be missing something since I don't know the codebase at all, but TrackConnectionState doesn't seem to be used anywhere in `mautrix/signal` & `mautrix/go`:
https://github.com/mautrix/signal/blob/25ba56bf9bf04c4154f5a41b903156207a45c874/metrics.go#L212

I'm currently on 103666990f30a692c63dd84a499b0dd390cef8a4.

My configuration looks like this:

<details><summary>signal.yml</summary>

```yaml
homeserver:
    address: https://nicht-so.sexy
    domain: nicht-so.sexy
appservice:
    address: http://bridges.soost.wireguard.ist.nicht-so.sexy:8082
    hostname: bridges.soost.wireguard.ist.nicht-so.sexy
    port: 8082
    database:
        type: postgres
        uri: postgres:///signalbridge?sslmode=disable&host=/run/postgresql
    id: signal
    bot:
        username: signalbot
        displayname: Signal bridge bot
        avatar: mxc://maunium.net/wPJgTQbZOtpBFmDNkiNEMDUp
    ephemeral_events: true
    as_token: redacted
    hs_token: redacted
metrics:
    enabled: true
    listen: 0.0.0.0:7981
signal:
    device_name: mautrix-signal
bridge:
    username_template: "signal_{{.}}"
    displayname_template: '{{or .ProfileName .PhoneNumber "Unknown user"}}'
    note_to_self_avatar: mxc://maunium.net/REBIVrqjZwmaWpssCZpBlmlL
    portal_message_buffer: 128
    delivery_receipts: false
    public_portals: false
    provisioning:
        prefix: /_matrix/provision
        shared_secret: generate
        debug_endpoints: false
    command_prefix: "!signal"
    permissions:
        '*': relay
        '@ma27:nicht-so.sexy': "admin"
        nicht-so.sexy: "user"
logging:
    min_level: debug
    writers:
    - type: stdout
      format: pretty-colored
```

</details>

But perhaps I'm just holding it wrong?
