### ISSUE TITLE
double puppeting - confusing chat layout in matrix client

### ISSUE THREAD

**Issue by neonblind** [mautrix/signal#520]
After installing the signal go-based bridge, messages I (Person A) send from official signal client seems to be like there is a third person in the room. 

old bridge

```
                                       Person A (Element client)
                                       Person A (native client)
Person B (native client) 

```

go bridge

```
                                       Person A (Element client)
Person A (native client)
Person B (native client) 

```

is this expected behavior or a bug?

**Comment by tulir** [comment]
That is expected when double puppeting is not enabled

**Comment by neonblind** [comment]
Hmm, I used appservice method and restart everything afterwards

mautrix-signal puppet.yaml
```
# The ID doesn't really matter, put whatever you want.
id: doublepuppet
# The URL is intentionally left empty (null), as the homeserver shouldn't
# push events anywhere for this extra appservice. If you use a
# non-spec-compliant server, you may need to put some fake URL here.
url:
# Generate random strings for these three fields. Only the as_token really
# matters, hs_token is never used because there's no url, and the default
# user (sender_localpart) is never used either.
as_token: abc123
hs_token: abc456
sender_localpart: abc789
# Bridges don't like ratelimiting. This should only apply when using the
# as_token, normal user tokens will still be ratelimited.
rate_limited: false
namespaces:
  users:
  # Replace your\.domain with your server name (escape dots for regex)
  - regex: '@.*:domain\.dedyn\.io'
    # This must be false so the appservice doesn't take over all users completely.
    exclusive: false
```

mautrix-signal config.yaml:
```
login_shared_secret_map:
        domain.dedyn.io: "as_token:abc123"
```

matrix homeserver.yaml:
```
app_service_config_files:
- /home/user/mautrix-signal/registration.yaml
- /home/user/mautrix-signal/puppet.yaml
```

something wrong?
