### ISSUE TITLE
double puppeting stopped working with the shared secret method

### ISSUE THREAD

**Issue by tom-ch1** [mautrix/signal#542]
after an update to 0.7.0 (or maybe before), double puppeting stopped working. I tried to set it up using shared secret method described in https://docs.mau.fi/bridges/general/double-puppeting.html as well as trying to interpret the autogenerated config as well as the migrated config generated by the 0.7.0 update (see also #541)

environment:
* debian bookworm
* matrix-synapse 1.113.0+bookworm1
* mautrix-signal-amd64_v0.7.0 (updated from v0.6.0 and from earlier legacy versions)

relevant section in homeserver.yaml:
```
modules:
  - module: shared_secret_authenticator.SharedSecretAuthProvider
    config:
      shared_secret: "myVerySecretString"
      m_login_password_support_enabled: true
      com_devture_shared_secret_auth_support_enabled: false
```

relevant section in config.yaml:
```
homeserver:
    address: https://matrix.my.server.org
    domain: my.server.org
[... snip... ]
double_puppet:
    servers:
        anotherserver.example.org: https://matrix.anotherserver.example.org
    allow_discovery: false
    secrets:
        my.server.org: as_token:"myVerySecretString"
```
I tried with or without quotes around myVerySecretString, both did not work

mautrix-signal log:
```{"level":"error","user_mxid":"####","action":"setup double puppet","error":"failed to GET /_matrix/client/v3/account/whoami: M_UNKNOWN_TOKEN (HTTP 401): Invalid access token passed.","time":"2024-09-03T13:41:50.658062507+02:00","message":"Failed to create new user intent"}```

matrix-synapse log:
```2024-09-03 13:41:50,657 - synapse.api.auth.internal - 287 - WARNING - GET-60099 - Invalid access token in auth: <class 'pymacaroons.exceptions.MacaroonDeserializationException'> cannot determine data format of binary-encoded macaroon.```
