### ISSUE TITLE
Registering the bridge with Conduwuit leads to `duplicate field receive_ephemeral` error

### ISSUE THREAD

**Issue by clement-escolano** [mautrix/signal#580]
When following the documentation to register the bridge with the Matrix server, I generated the registration file that looks like:
```
id: signal
url: http://localhost:29328
as_token: redacted
hs_token: redacted
sender_localpart: redacted
rate_limited: false
namespaces:
    users:
        - regex: ^@signalbot:redacted$
          exclusive: true
        - regex: ^@signal_.*:redacted$
          exclusive: true
de.sorunome.msc2409.push_ephemeral: true
receive_ephemeral: true
```

Then I registered it with Conduwuit by sending the command to the user. However, at this step, there is the following error:
```
Could not parse appservice config as YAML: duplicate field receive_ephemeral
```

So I removed it and it worked but now the "read status" does not propagate from Matrix to Signal and I assume this is related.

Is this normal to have this error with the default registration file?

For reference:
Signal bridge version: v0.7.5
Conduwuit version: v0.5.0-rc2
