### ISSUE TITLE
Matrix -> Signal : Read receipts not sent ?

### ISSUE THREAD

**Issue by c4software** [mautrix/signal#601]
Hi,

The bridge is working very well overall! However, I'm encountering an issue with **read receipts** not being sent from Matrix to Signal. There are no visible errors in the logs, but the receipts simply don't appear to be delivered to Signal.

Here is my current configuration:

```yaml
# Config options that affect the Matrix connector of the bridge.
matrix:
  message_status_events: false
  delivery_receipts: true
  message_error_notices: true
  sync_direct_chat_list: true
  federate_rooms: true
  upload_file_threshold: 5242880
```

I'm using Element as the Matrix client and Tuwunel as the server. Read receipts between users on the same server are working perfectly.

Is there anything I might be missing in the configuration?
