### ISSUE TITLE
Nicknames are not shown

### ISSUE THREAD

**Issue by pwall2222** [mautrix/signal#604]
Contact nicknames are not shown in the relay

**Comment by bernikr** [comment]
just to add more details to this:

It would be great to add an `{{.Nickname}}` option (or even seperated options for first and last name) to the following config:

```yaml
network:
    # Displayname template for Signal users.
    # {{.ProfileName}} - The Signal profile name set by the user.
    # {{.ContactName}} - The name for the user from your phone's contact list. This is not safe on multi-user instances.
    # {{.PhoneNumber}} - The phone number of the user.
    # {{.UUID}} - The UUID of the Signal user.
    # {{.AboutEmoji}} - The emoji set by the user in their profile.
    displayname_template: '{{or .ContactName .ProfileName .PhoneNumber "Unknown user"}}'
```
